#!/bin/bash

# Manual Deployment Guide - Step by Step
# Gunakan ini jika deploy-vercel.sh tidak jalan

echo "🚀 Vercel Deployment - Manual Guide"
echo "===================================="
echo ""

# Color codes
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}STEP 1: Install Vercel CLI${NC}"
echo "------------------------------"
echo "Run this command in your terminal:"
echo ""
echo -e "${GREEN}npm install -g vercel${NC}"
echo ""
read -p "Press Enter when Vercel CLI is installed..."

echo ""
echo -e "${BLUE}STEP 2: Login to Vercel${NC}"
echo "------------------------------"
echo "Run this command:"
echo ""
echo -e "${GREEN}vercel login${NC}"
echo ""
echo "Follow the instructions in your browser."
echo ""
read -p "Press Enter when you're logged in..."

echo ""
echo -e "${BLUE}STEP 3: Link Project${NC}"
echo "------------------------------"
echo "Run this command:"
echo ""
echo -e "${GREEN}vercel link${NC}"
echo ""
echo "Follow the prompts to link to your project."
echo ""
read -p "Press Enter when project is linked..."

echo ""
echo -e "${BLUE}STEP 4: Add Environment Variables${NC}"
echo "------------------------------"
echo "Go to Vercel Dashboard:"
echo "  https://vercel.com/dashboard"
echo ""
echo "Then:"
echo "  1. Select your project"
echo "  2. Go to Settings → Environment Variables"
echo "  3. Click 'Add New' for each variable:"
echo ""
echo -e "${YELLOW}Required Variables:${NC}"
echo ""
echo "1. POSTGRES_PRISMA_URL"
echo "   Value: postgres://df1f6bb92f9f575ea1d870a67fb2c19f2b50cd9dfb9056cb1561c2f46c721122:sk_OxeMNEvg4SxBP76Kwv6zt@db.prisma.io:5432/postgres?sslmode=require&pgbouncer=true&connect_timeout=15"
echo "   Environments: Production, Preview, Development"
echo ""
echo "2. POSTGRES_URL_NON_POOLING"
echo "   Value: postgres://df1f6bb92f9f575ea1d870a67fb2c19f2b50cd9dfb9056cb1561c2f46c721122:sk_OxeMNEvg4SxBP76Kwv6zt@db.prisma.io:5432/postgres?sslmode=require"
echo "   Environments: Production, Preview, Development"
echo ""
echo "3. POSTGRES_URL"
echo "   Value: postgres://df1f6bb92f9f575ea1d870a67fb2c19f2b50cd9dfb9056cb1561c2f46c721122:sk_OxeMNEvg4SxBP76Kwv6zt@db.prisma.io:5432/postgres?sslmode=require&pgbouncer=true"
echo "   Environments: Production, Preview, Development"
echo ""
echo "4. NEXTAUTH_SECRET"
echo "   Generate with: openssl rand -base64 32"
echo "   Environments: Production, Preview, Development"
echo ""
echo "5. NEXTAUTH_URL"
echo "   Leave empty for now (fill after deployment)"
echo "   Environments: Production"
echo ""
read -p "Press Enter when all environment variables are added..."

echo ""
echo -e "${BLUE}STEP 5: Deploy to Vercel${NC}"
echo "------------------------------"
echo "Run this command:"
echo ""
echo -e "${GREEN}vercel --prod${NC}"
echo ""
echo "Wait for deployment to complete (2-3 minutes)."
echo ""
read -p "Press Enter when deployment is done..."

echo ""
echo -e "${BLUE}STEP 6: Update NEXTAUTH_URL${NC}"
echo "------------------------------"
echo "1. Go to Vercel Dashboard"
echo "2. Copy your deployment URL (e.g., https://ayamgeprekku.vercel.app)"
echo "3. Go to Settings → Environment Variables"
echo "4. Edit NEXTAUTH_URL:"
echo "   Production: https://your-domain.vercel.app"
echo "5. Click Save"
echo ""
echo "6. Go to Deployments tab"
echo "7. Click 'Redeploy'"
echo ""
read -p "Press Enter when done..."

echo ""
echo -e "${GREEN}🎉 Deployment Complete!${NC}"
echo "===================================="
echo ""
echo "Your app is now live!"
echo ""
echo -e "${YELLOW}Next Steps:${NC}"
echo "1. Test your app at the deployment URL"
echo "2. Check all features are working"
echo "3. Monitor logs in Vercel Dashboard"
echo ""
echo -e "${YELLOW}To view database:${NC}"
echo "  Run: bunx prisma studio"
echo ""
echo -e "${YELLOW}To update code:${NC}"
echo "  1. git add . && git commit -m 'your changes'"
echo "  2. git push origin master"
echo "  3. Vercel will auto-deploy"
echo ""
